name: run-dbt-ci

on:
  pull_request:
    branches:
      - main
    paths:
      - "dbt/**"

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dbt_docs_generate:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: dbt
      DBT_PROJECT_DIR: dbt
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.29"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Generate Requirements
        run: uv export --format requirements-txt --no-hashes --group sqlfluff_ci > requirements_sqlfluff_ci.txt
      - name: Install Dependencies
        run: pip install -r requirements_sqlfluff_ci.txt
      - name: Run dbt deps
        run: dbt deps
      - name: Run dbt Docs Generate
        run: dbt docs generate --profile cicd --empty-catalog
  sqlfluff:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: dbt
      DBT_PROJECT_DIR: dbt
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.29"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Generate Requirements
        run: uv export --format requirements-txt --no-hashes --group sqlfluff_ci > requirements_sqlfluff_ci.txt
      - name: Install Dependencies
        run: pip install -r requirements_sqlfluff_ci.txt
      - name: Run dbt deps
        run: dbt deps
      - name: Run SQLFluff
        run: sqlfluff lint dbt
